### ISSUE TITLE
在build.gradle引用的时候报错

### ISSUE THREAD

**Issue by xinshengBoy** [feiyuu/FloatingView#1]
在未引用之前
![QQ截图20200325142229](https://user-images.githubusercontent.com/16789055/77507888-4e906800-6ea4-11ea-9d85-559ca4bf7056.png)

引用之后
![QQ截图20200325142325](https://user-images.githubusercontent.com/16789055/77507901-58b26680-6ea4-11ea-9a8a-a9917cdb0a78.png)

报错的提示是：
Dependencies using groupId `com.android.support` and `androidx.*` can not be combined but found `IdeMavenCoordinates{myGroupId='com.android.support', myArtifactId='support-media-compat', myVersion='27.1.1', myPacking='aar', myClassifier='null'}` and `IdeMavenCoordinates{myGroupId='androidx.fragment', myArtifactId='fragment', myVersion='1.1.0', myPacking='aar', myClassifier='null'}` incompatible dependencies

这应该是因为适配androidx导致的吧，如果不适配androidx，是不是该有一个解决的方案呢，望解答

**Comment by feiyuu** [comment]
已去掉所有依赖，不会再有任何冲突了，优化到了基本完整的体验，欢迎升到1.0.6体验。
![微信图片_20200326211358](https://user-images.githubusercontent.com/25423685/77651395-aebc0280-6fa7-11ea-8450-f8a161ad9d72.png)
